# Generated by Django 5.2.8 on 2025-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('proceso', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
